spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/backendtechassignment"
    username: "api"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
tier-limits:
  free: 3
  basic: 10
  premium: 20
  business: 100